### ISSUE TITLE
Urza, Chief Artificer Missing Token

### ISSUE THREAD

**Issue by jonidcrushfire** [Cockatrice/Magic-Token#197]
The construct token for Urza, Chief Artificer is missing. It is the 0/0 artifact creature with "This creature gets +1/+1 for each artifact you control."

Please let me know what information you require and I will get it to you.

**Comment by ebbit1q** [comment]
it seems like BRC tokens are missing, these are the cards that need adding: https://scryfall.com/sets/tbrc

if you'd like to contribute to the tokens, you can add these card relations to the tokens.xml file in this repo and suggest the changes.

**Comment by SlightlyCircuitous** [comment]
I think this token is currently in Cockatrice. It was printed in DMR and was added with the rest of the DMR tokens. Since Urza, Chief Artificer was printed in a promo set and not in DMR, I missed adding it to the token file so it just lacks the card menu 'create token' functionality. I will put in a PR to fix that, but until that is merged, you should be able to create the token manually by opening the play area menu and using the 'create token' option to search for it rather than creating it via Urza.

**Comment by ebbit1q** [comment]
fixed by #199
