### ISSUE TITLE
The Undercity should be able to create a Treasure Token

### ISSUE THREAD

**Issue by iceaquilegia** [Cockatrice/Magic-Token#230]
As the title suggests the Undercity can create the 4/1 Skeleton Token from "Catacombs" but can't create the Treasure Token from "Stash"

![image](https://github.com/Cockatrice/Cockatrice/assets/14921794/3f320148-1ed3-44e0-8c9d-144225357bb9)

**Comment by tooomm** [comment]
Hi @iceaquilegia 
Thanks for reporting this token issue within Cockatrice. We maintain a dedicated place where our token database with its card relations is stored and updated. It's not an issue with the Cockatrice app itself. 
Hence ebbit moved it here.

The issue you are describing was due to a single treasure relation not being updated to the correct, full token name. So Cockatrice could not find the link and display the create option.

It's fixed now and if you download the newest card & token updates in Cockatrice (help menu). You can use it right away! Enjoy 😀
