### ISSUE TITLE
Infect counter

### ISSUE THREAD

**Issue by ctrlaltca** [Cockatrice/Magic-Token#7]
User "Perfect" requested the card "Poison counter" to be ~~added and~~ related to cards producing infect counters.

EDIT: i see the card is already present in tokens.xml

**Comment by tooomm** [comment]
Since the [Experience](https://github.com/Cockatrice/Magic-Token/blob/master/tokens.xml#L4426) counter/token is reverse-related already that makes sense.

But this would mostly just be useful if you could create the "Poison counter" by right clicking on enemy cards as well... I don't think that's possible at the moment?
