### ISSUE TITLE
Related tokens for OGW and SOI

### ISSUE THREAD

**Issue by JineteDV** [Cockatrice/Magic-Token#9]
OSX 10.11.3 Cockatrice Ver 323fc06. I downloaded an xml from oracle just before writing this.

Clues aren't set as related cards for anything. None of the OGW or SOI permanents that make tokens have their tokens set as related cards.

**Comment by Psithief** [comment]
You have the clue tokens but not the related items? As I understand it, that should be impossible.

You can try downloading the tokens.xml manually, or updating your client to the latest development version.

If you cannot resolve this, you need to report the issue to Cockatrice/Cockatrice/issues, since it works on my machine and I cannot investigate further than that.
